name: CI/CD
'on':
  push:
    branches:
      - master
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release
      - name: Publish artifact
        run: dotnet publish --configuration Release --output ./publish
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: ./publish/
  deploy:
    runs-on: windows-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: app
          path: ./app
      - name: Deploy to Local PC via FTP
        env:
          FTP_HOST: '${{ secrets.FTP_HOST }}'
          FTP_USERNAME: '${{ secrets.FTP_USERNAME }}'
          FTP_PASSWORD: '${{ secrets.FTP_PASSWORD }}'
          FTP_DEPLOY_PATH: '${{ secrets.FTP_DEPLOY_PATH }}'
        run: |
          apt-get update
          apt-get install -y lftp
          lftp -d -c "
          open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST;
          mirror -R ./app $FTP_DEPLOY_PATH
          "
