name: CI/CD
'on':
  push:
    branches:
      - master
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --output ./build-output
      - name: Publish artifact
        run: dotnet publish --configuration Release --output ./publish
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: ./publish/
  deploy:
    runs-on: windows-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: app
          path: ./publish/
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: '${{ secrets.TOKEN }}'
          publish_dir: ./publish/
